(* val x = Grammar.addSymbols "S";
val x = Grammar.addSymbols "E";
val x = Grammar.addSymbols "E'";
val x = Grammar.addSymbols "T";
val x = Grammar.addSymbols "T'";
val x = Grammar.addTokens "+";
val x = Grammar.addSymbols "*";
val x = Grammar.addSymbols "N";
val x = Grammar.addSymbols "$";
val x = Grammar.addRule "S" [["E", "$"]];
val x = Grammar.addRule "E" [["T", "E'"]];
val x = Grammar.addRule "E'" [["T", "E'"] , []];
val x = Grammar.addRule "T" [["N", "T'"]];
val x = Grammar.addRule "T'" [["*", "N" , "T'"] , []];
val x = Grammar.printRules() *)

val x = Grammar.addSymbols "S";
val x = Grammar.addSymbols "A";
val x = Grammar.addSymbols "B'";
val x = Grammar.addSymbols "D";
val x = Grammar.addTokens "a";
val x = Grammar.addTokens "b";
val x = Grammar.addRule "S" [["D", "B"]];
val x = Grammar.addRule "A" [["a", "A"] , []];
val x = Grammar.addRule "B" [["b", "B"] , []];
val x = Grammar.addRule "D" [["A", "B"]];
val x = Grammar.printRules()
